apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-2-deployment
  labels:
    app: backend-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-2
  template:
    metadata:
      labels:
        app: backend-2
    spec:
      containers:
      - image: gcr.io/speedback-303112/backend-2
        name: backend-2