apiVersion: v1
kind: Service
metadata:
  labels:
    app: "backend-2"
  name: "backend-2-service"
  namespace: default
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: "backend-2"
  type: ClusterIP
