FROM node:14-alpine
WORKDIR /app
ENV REACT_APP_ENV "production"
COPY . .
RUN yarn run build 
FROM mhart/alpine-node
RUN yarn global add serve
WORKDIR /app
COPY --from=0 /app/build .
CMD ["serve", "-p", "3000", "-s", "."]