# docker-compose.yml
version: "3.3"
services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm start

  backend:
    build: ./backend
    ports:
      - 4000:4000
    command: npm start

  backend-2:
    build: ./backend-2
    command: npm start
