apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: backend